# -*- coding: utf-8 -*-
"""CS3793_5233_assignment2_xpn197.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1AxyenSR3NisdPJq_LzyehXdhsnQ-wMxR

# UTSA CS 3793/5233: Assignment-2

**Last Name - First Name - (abc123)**

## Learning Objectives



*   Game Playing
*   Chess - Board Setup & Rules
*   Adversarial Search
*   AI - Random vs MinMax

## Description

This assignment is focused on **game playing** and creating a proper **AI for chess**. 
In the following sections, you will complete a series of tasks to create a chess game board, rules for each chess piece, a Random AI and a MinMax AI that plays a game of chess for both players (white and black).

The base structure of the code is provided. You are supposed to write code for each of the functions. Comments are provided on what should be done. You **CANNOT** use a complete chess library and change the base code structure completely. However, you **CAN** change the code layout and name/format of the functions.

#Chess Board Setup & Rules

In this section, you will write code to import the necessary libraries and create:

1.   **ChessBoard** - This part will contain code to initialize the board, draw the board, get the board state and move piece.
2.   **ChessRules** - This part will contain code for the chess rules for each piece.

##Import Libraries

The code here will contain only **import** statements. A base list of the required libraries are already imported. You will most likely not need any other libraries, but if needed, add the import statements here. As mentioned before, you can not use any premade chess libraries.
"""

# your code goes here
import string
import random
import os
import sys
import time
from IPython.display import clear_output
import numpy as np
import copy

"""##ChessBoard

(10 points)

Fill the code in the code structure provided below for the ChessBoard. The main use of this code block write functions to initialize the board, draw the board, get the board state and move piece. You can add any other functions if needed.

"""

# you can add/change the input parameters for each function 
# you can change the function names and also add more functions if needed
currentWhite = False
def ChessBoardSetup():
    # initialize and return a chess board - create a 2D 8x8 array that has the value for each cell
    # USE the following characters for the chess pieces - lower-case for BLACK and upper-case for WHITE
    # . for empty board cell
    # p/P for pawn
    # r/R for rook
    # t/T for knight
    # b/B for bishop
    # q/Q for queen
    # k/K for king
    chessBoard = [["r","t","b","q","k","b","t","r"],
                  ["p","p","p","p","p","p","p","p"],
                  [".",".",".",".",".",".",".","."],
                  [".",".",".",".",".",".",".","."],
                  [".",".",".",".",".",".",".","."],
                  [".",".",".",".",".",".",".","."],
                  ["P","P","P","P","P","P","P","P"],
                  ["R","T","B","Q","K","B","T","R"]]
    return chessBoard

def DrawBoard(board):
    # write code to print the board - following is one print example
    # r t b q k b t r
    # p p p p p p p p
    # . . . . . . . .
    # . . . . . . . .
    # . . . . . . . .
    # . . . . . . . .
    # P P P P P P P P
    # R T B Q K B T R
    for i in board:
      for j in i:
        print(j, end = " ")
      print("")

def MovePiece(fromX, toX, fromY, toY):
    # write code to move the one chess piece
    # you do not have to worry about the validity of the move - this will be done before calling this function
    # this function will at least take the move (from-piece and to-piece) as input and return the new board layout
    
    temp = board[fromY][fromX]
    board[toY][toX] = temp
    board[fromY][fromX] = "."
    return board

"""##ChessRules

(50 points)

Fill the code in the code structure provided below for ChessRules. The main use of the code block is to write functions to design the rules for movement of each piece on the board. This block will also contain the function to check if the current player is in check, check-mate. You can also have functions that can return the current player's pieces that have legal moves in the current board state. 

Following are some **suggested** functions with the pseudocode provided. You can create/remove functions as needed.

"""

# return True if the input move (from-square and to-square) is legal, else False
# this is the KEY function which contains the rules for each piece type 
def IsMoveLegal(fromX, toX, fromY, toY):
    
    # input is from-square and to-square
    # use the input and the board to get the from-piece and to-piece

    # if from-square is the same as to-square
        # return False
    if fromX == toX and fromY == toY:
      return False
    # if the from-piece is a "pawn"
        ## case - pawn wants to move one step forward (or backward if white)
        # if to-square is empty and is in the same column as the from-square
            # return True
        ## case - pawn can move two spaces forward (or backward if white) ONLY if pawn on starting row
        # else if to-square is empty and from-square-row = 2 (or 7 if white) and to-square-row = from-square-row + 2 (or -2 if white)
            # if IsClearPath() - a clear path exists between from-square and to-square
                # return True
        ## case - pawn attacks the enemy piece if diagonal
        # else if there is piece diagonally forward (or backward if white) and that piece belongs to the enemy team
            # return True
    if board[fromY][fromX] == 'p' or board[fromY][fromX] == 'P':
      yRange = toY - fromY
      xRange = toX - fromX
      if currentWhite == True and xRange == 0 and yRange == -1:
        if board[toY][toX] == '.' and fromX == toX:
          return True
      elif currentWhite == False and xRange == 0 and yRange == 1:
        if board[toY][toX] == '.' and fromX == toX:
          return True
      elif (yRange == 2 or yRange == -2) and xRange == 0:
        if board[toY][toX] == '.' and fromY == 1 and toY == fromY + 2:
          if IsClearPath(fromX, toX, fromY, toY):
            return True
        elif board[toY][toX] == '.' and fromY == 6 and toY == fromY - 2:
          if IsClearPath(fromX, toX, fromY, toY):
            return True
      elif (xRange == 1 or xRange == -1) and (yRange == 1 or yRange == -1):
        if currentWhite == True:
          if board[toY][toX].islower():
            return True
        elif currentWhite == False:
          if board[toY][toX].isupper():
            return True

    # else if the from-piece is a "rook"
        # if to-square is either in the same row or column as the from-square
            # if to-square is either empty or contains a piece that belongs to the enemy team
                # if IsClearPath() - a clear path exists between from-square and to-square
                    # return True
    elif board[fromY][fromX] == "r" or board[fromY][fromX] == "R":
      if fromX == toX or fromY == toY:
        if board[toY][toX] == '.' or ((currentWhite == False and board[toY][toX].isupper()) or (currentWhite == True and board[toY][toX].islower())):
          if IsClearPath(fromX, toX, fromY, toY):
            return True
    # else if the from-piece is a "bishop"
        # if to-square is diagonal wrt from-square
            # if to-square is either empty or contains a piece that belongs to the enemy te
                # if IsClearPath() - a clear path exists between from-square and to-square
                    # return True
    elif board[fromY][fromX] == 'b' or board[fromY][fromX] == 'B':
      if fromX-fromY == toX-toY or fromX+fromY == toX+toY:
        if board[toY][toX] == '.' or ((currentWhite == False and board[toY][toX].isupper()) or (currentWhite == True and board[toY][toX].islower())):
          if IsClearPath(fromX, toX, fromY, toY):
            return True
    # else if the from-piece is a "queen"
        ## SAME as "rook"
        # if to-square is either in the same row or column as the from-square
            # if to-square is either empty or contains a piece that belongs to the enemy team
                # if IsClearPath() - a clear path exists between from-square and to-square
                    # return True
        ## SAME as "bishop"
        # if to-square is diagonal wrt from-square
            # if to-square is either empty or contains a piece that belongs to the enemy team
                # if IsClearPath() - a clear path exists between from-square and to-square
                    # return True
    elif board[fromY][fromX] == 'q' or board[fromY][fromX] == 'Q':
      #rook logic
      if fromX == toX or fromY == toY:
        if board[toY][toX] == '.' or ((currentWhite == False and board[toY][toX].isupper()) or (currentWhite == True and board[toY][toX].islower())):
          if IsClearPath(fromX, toX, fromY, toY):
            return True
      #bishop logic
      if fromX-fromY == toX-toY or fromX+fromY == toX+toY:
        if board[toY][toX] == '.' or ((currentWhite == False and board[toY][toX].isupper()) or (currentWhite == True and board[toY][toX].islower())):
          if IsClearPath(fromX, toX, fromY, toY):
            return True
    # else if the from-piece is a "knight"
        # calculate the col-diff = to-square-col - from-square-col
        # calculate the row-diff = to-square-row - from-square-row
        # if to-square is either empty or contains a piece that belongs to the enemy team
            # return True for any of the following cases:
                # col-diff = 1 & row_dif = -2
                # col-diff = 2 & row_dif = -1
                # col-diff = 2 & row_dif = 1
                # col-diff = 1 & row_dif = 2
                # col-diff = -1 & row_dif = -2
                # col-diff = -2 & row_dif = -1
                # col-diff = -2 & row_dif = 1
                # col-diff = -1 & row_dif = 2
    elif board[fromY][fromX] == 't' or board[fromY][fromX] == 'T':
      colDif = toX - fromX
      rowDif = toY - fromY
      if board[toY][toX] == '.' or ((currentWhite == True and board[toY][toX].islower()) or (currentWhite == False and board[toY][toX].isupper())):
        if (colDif == 1 and rowDif == -2) or (colDif == 2 and rowDif == -1) or (colDif == 2 and rowDif == 1) or (colDif == 1 and rowDif == 2):
          return True
        elif (colDif == -1 and rowDif == -2) or (colDif == -2 and rowDif == -1) or (colDif == -2 and rowDif == 1) or (colDif == -1 and rowDif == 2):
          return True
    # else if the from-piece is a "king"
        # calculate the col-diff = to-square-col - from-square-col
        # calculate the row-diff = to-square-row - from-square-row
        # if to-square is either empty or contains a piece that belongs to the enemy team
            # return True for any of the following cases:
                # abs(col-diff) = 1 & abs(row_dif) = 0
                # abs(col-diff) = 0 & abs(row_dif) = 1
                # abs(col-diff) = 1 & abs(row_dif) = 1
    elif board[fromY][fromX] == 'k' or board[fromY][fromX] == 'K':
      colDif = toX - fromX
      rowDif = toY - fromY
      if board[toY][toX] == '.' or ((currentWhite == False and board[toY][toX].isupper()) or (currentWhite == True and board[toY][toX].islower())):
        if (abs(colDif) == 1 and abs(rowDif) == 0) or (abs(colDif) == 0 and abs(rowDif) == 1) or (abs(colDif) == 1 and abs(rowDif) == 1):
          return True
    # return False - if none of the other True's are hit above
    return False


# gets a list of legal moves for a given piece
# input = from-square
# output = list of to-square locations where the piece can move to
#def GetListOfLegalMoves():
    # input is the current player and the given piece as the from-square
    # initialize the list of legal moves, i.e., to-square locations to []
    # go through all squares on the board
    # for the selected square as to-square
        # call IsMoveLegal() with input as from-square and to-square and save the returned value
        # if returned value is True
            # call DoesMovePutPlayerInCheck() with input as from-square and to-square and save the returned value
            # if returned value is False
                # append this move (to-square) as a legal move
    # return the list of legal moves, i.e., to-square locations
def GetListOfLegalMoves(fromX, fromY):
  legalMoves = []
  
  for count,y in enumerate(board):
    for count2,x in enumerate(y):
      toX = count2
      toY = count
      result = IsMoveLegal(fromX, toX, fromY, toY)
      if result:
        result2 = DoesMovePutPlayerInCheck(fromX, toX, fromY, toY)
        if result2 == False:
          legalMoves.append([count,count2])
  return legalMoves

  


# gets a list of all pieces for the current player that have legal moves
#def GetPiecesWithLegalMoves():
    # initialize the list of pieces with legal moves to []
    # go through all squares on the board
    # for the selected square
        # if the square contains a piece that belongs to the current player's team
            # call GetListOfLegalMoves() to get a list of all legal moves for the selected piece / square 
            # if there are any legel moves
                # append this piece to the list of pieces with legal moves
    # return the final list of pieces with legal moves
def GetPiecesWithLegalMoves():
  
  pieces = []
  temp = []
  for count, y in enumerate(board):
    for count2, x in enumerate(y):
      if currentWhite == True and board[count][count2].isupper():
        temp = GetListOfLegalMoves(count2, count)
        if temp:
          pieces.append([count, count2])
      elif currentWhite == False and board[count][count2].islower():
        temp = GetListOfLegalMoves(count2, count)
        if temp:
          pieces.append([count, count2])
  return pieces


# returns True if the current player is in checkmate, else False
#def IsCheckmate():
    # call GetPiecesWithLegalMoves() to get all legal moves for the current player
    # if there is no piece with any valid move
        # return True
    # else
        # return False
def IsCheckmate():
  
  legalMoves = GetPiecesWithLegalMoves()
  if legalMoves:
    return True
  else:
    return False


# returns True if the given player is in Check state
#def IsInCheck():
    # find given player's King's location = king-square
    # go through all squares on the board
        # if there is a piece at that location and that piece is of the enemy team
            # call IsMoveLegal() for the enemy player from that square to the king-square
            # if the value returned is True
                # return True
            # else
                # do nothing and continue 
    # return False at the end
  #kingInY, kingInX = np.where(chessBoard[][] == 'k')

def IsInCheck():
  
  kingInY = 0
  kingInX = 0
  for count, y in enumerate(board):
    for count2, x in enumerate(y):
      if currentWhite == False and board[count][count2] == 'k':
        kingInY = count
        kingInX = count2
      elif currentWhite == True and board[count][count2] == 'K':
        kingInY = count
        kingInX = count2

  for count,y in enumerate(board):
    for count2,x in enumerate(y):
      if currentWhite == True and (board[count][count2] != '.' and board[count][count2].islower()):
        value = IsMoveLegal(count2, kingInX, count, kingInY)
        if value:
          return True
      elif currentWhite == False and (board[count][count2] != '.' and board[count][count2].isupper()):
        value = IsMoveLegal(count2, kingInX, count, kingInY)
        if value:
          return True
  return False


# helper function to figure out if a move is legal for straight-line moves (rooks, bishops, queens, pawns)
# returns True if the path is clear for a move (from-square and to-square), non-inclusive
#def IsClearPath():
    # given the move (from-square and to-square)

    # if the from and to squares are only one square apart
        # return True
    # else
        # if to-square is in the +ve vertical direction from from-square
            # new-from-square = next square in the +ve vertical direction
        # else if to-square is in the -ve vertical direction from from-square
            # new-from-square = next square in the -ve vertical direction
        # else if to-square is in the +ve horizontal direction from from-square
            # new-from-square = next square in the +ve horizontal direction
        # else if to-square is in the -ve horizontal direction from from-square
            # new-from-square = next square in the -ve horizontal direction
        # else if to-square is in the SE diagonal direction from from-square
            # new-from-square = next square in the SE diagonal direction
        # else if to-square is in the SW diagonal direction from from-square
            # new-from-square = next square in the SW diagonal direction
        # else if to-square is in the NE diagonal direction from from-square
            # new-from-square = next square in the NE diagonal direction
        # else if to-square is in the NW diagonal direction from from-square
            # new-from-square = next square in the NW diagonal direction

    # if new-from-square is not empty
        # return False
    # else
        # return the result from the recursive call of IsClearPath() with the new-from-square and to-square
def IsClearPath(fromX, toX, fromY, toY):
  
  yRange = fromY - toY
  xRange = fromX - toX
  if xRange in range(-1,1) and yRange in range(-1,1):
    return True
  else:
    if yRange > 0 and xRange == 0:
      newSqX = fromX
      newSqY = fromY - 1
    elif yRange < 0 and xRange == 0:
      newSqX = fromX
      newSqY = fromY + 1
    elif xRange < 0 and yRange == 0:
      newSqX = fromX + 1
      newSqY = fromY
    elif xRange > 0 and yRange == 0:
      newSqX = fromX - 1
      newSqY = fromY
    elif yRange < 0 and xRange < 0:
      newSqX = fromX + 1
      newSqY = fromY + 1
    elif yRange < 0 and xRange > 0:
      newSqX = fromX - 1
      newSqY = fromY + 1
    elif yRange > 0 and xRange < 0:
      newSqX = fromX + 1
      newSqY = fromY - 1
    elif yRange > 0 and xRange > 0:
      newSqX = fromX - 1
      newSqY = fromY - 1
  
  if board[newSqY][newSqX] != '.':
    return False
  else:
    return IsClearPath(newSqX, toX, newSqY, toY)


# makes a hypothetical move (from-square and to-square)
# returns True if it puts current player into check
#def DoesMovePutPlayerInCheck():
    # given the move (from-square and to-square), find the 'from-piece' and 'to-piece'
    # make the move temporarily by changing the 'board'
    # Call the IsInCheck() function to see if the 'player' is in check - save the returned value
    # Undo the temporary move
    # return the value saved - True if it puts current player into check, False otherwise
def DoesMovePutPlayerInCheck(fromX, toX, fromY, toY):
  global board
  tempBoard = copy.deepcopy(board)
  MovePiece(fromX, toX, fromY, toY)
  value = IsInCheck()
  board = copy.deepcopy(tempBoard)
  return value

"""#Artificial Intelligence

In this section, you will write code for the Artificial Intelligence (AI) that will play a game of chess. You will write 2 types of AI:

1.   **RandomAI** - This part will contain code for moving a chess piece randomly.
2.   **MinMaxAI** - This part will contain code for moving a chess piece using the MinMax strategy discussed in the lecture.

##RandomAI

(10 points)

Complete the function below that will perform a random move for the given player. The function will return the move (from-piece and to-piece). You will most likely not need to write any other function, but you can, if needed.
"""

def GetRandomMove():
    # pick a random piece and a random legal move for that piece
    pieces = GetPiecesWithLegalMoves()
    #print(pieces)
    piece = random.choice(pieces)
    #print(piece)
    moves = GetListOfLegalMoves(piece[1], piece[0])
    #print(moves)
    move = random.choice(moves)
    #print(move)
    value = [piece, move]
    return value

"""##MinMaxAI

(50 points)

Complete the functions below that will perform a move for the given player using the MinMax AI strategy. One function will evaluate the board if a move is performed - give score for each of piece and calculate the score for the entire chess board. In the second function you will write actual code for the MinMax strategy and return the move (from-piece and to-piece). To get the allocated points, searching should be **2-ply (one Max and one Min)**. You will most likely not need to write any other function, but you can, if needed.

## Extra Credit

*   **(5 points)** Modify the above MinMax strategy to be **4-ply (one Max, one Min, one Max, one Min)**.
*   **(10 points)** Perform **alpha-beta pruning** for the MinMax strategy.
"""

#def evl():
    # this function will calculate the score on the board, if a move is performed
    # give score for each of piece and calculate the score for the chess board

def evl():
  whiteScore = 0
  blackScore = 0
  for count, y in enumerate(board):
    for count2, x in enumerate(y):
      if board[count][count2].isupper() and board[count][count2] == 'P':
          whiteScore += 1
      elif board[count][count2].isupper() and board[count][count2] == 'R':
          whiteScore += 5
      elif board[count][count2].isupper() and board[count][count2] == 'T':
          whiteScore += 3
      elif board[count][count2].isupper() and board[count][count2] == 'B':
          whiteScore += 3
      elif board[count][count2].isupper() and board[count][count2] == 'Q':
          whiteScore += 9
      elif board[count][count2].islower() and board[count][count2] == 'p':
          blackScore += 1
      elif board[count][count2].islower() and board[count][count2] == 'r':
          blackScore += 5
      elif board[count][count2].islower() and board[count][count2] == 't':
          blackScore += 3
      elif board[count][count2].islower() and board[count][count2] == 'b':
          blackScore += 3
      elif board[count][count2].islower() and board[count][count2] == 'q':
          blackScore += 9
  if currentWhite == True:
    return whiteScore
  elif currentWhite == False:
    return blackScore

#def GetMinMaxMove():
    # return the best move for the current player using the MinMax strategy
    # to get the allocated points, searching should be 2-ply (one Max and one Min)

    # Following is the setup for a 2-ply game

    # pieces = GetPiecesWithLegalMoves(curPlayer)
    # for each piece in pieces
        # moves = GetListOfLegalMoves(curPlayer, piece)
        # for move in moves
            # perform the move temporarily
            # enemyPieces = GetPiecesWithLegalMoves(enemyPlayer)
            # for enemyPiece in penemyPiecesieces
                # enemyMoves = GetListOfLegalMoves(enemyPlayer, enemyPiece)
                # for enemyMove in enemyMoves
                    # perform the enemyMove temporarily
                    # res = evl(curPlayer)
                    # update the bestEnemyMove -- this is the MIN player trying to minimize from the 'res' evaluation values
                    # undo the enemyMove
            # update the bestMove -- this is the MAX player trying to maximize from the 'bestEnemyMove' evaluation values
            # undo the move
    # if bestMove found without any doubt, pick that
    # if bestMove not found, pick randomly

    # OPTIONAL -- sometimes automated chess keeps on performing the moves again and again
    # e.g., move king left one square and then move king back - repeat
    # For this you will need to remember the previous move and see if the current best move is not the same and opposite as the previous move
    # If so, pick the second best move instead of the best move
def GetMinMaxMove():
  global board
  global currentWhite
  score = 0
  bestEnemyMove = 999
  worstEnemyMove = 0
  repeats = 0
  pieces = GetPiecesWithLegalMoves()
  for piece in pieces:
    moves = GetListOfLegalMoves(piece[1], piece[0])
    for move in moves:
      tempBoard = copy.deepcopy(board)
      board = MovePiece(piece[1], move[1], piece[0], move[0])
      currentWhite = not currentWhite
      enemyPieces = GetPiecesWithLegalMoves()
      for enemyPiece in enemyPieces:
        enemyMoves = GetListOfLegalMoves(enemyPiece[1], enemyPiece[0])
        for enemyMove in enemyMoves:
          tempBoard2 = copy.deepcopy(board)
          board = MovePiece(enemyPiece[1], enemyMove[1], enemyPiece[0], enemyMove[0])
          res = evl()
          if res > score:
            score = res
            bestMove = [piece, move]
          if res < bestEnemyMove:
            bestEnemyMove = res
            enMove = enemyMove
            repeats = 0
          if bestEnemyMove == res:
            repeats += 1
          board = tempBoard2
        
      board = tempBoard
      currentWhite = not currentWhite
  return bestMove

"""#Game Setup & Main Loop

(05 points)

Write code below to have a game-play between two AIs - Random vs MinMax. For each iteration, draw the board before and after a turn. 
"""

# initialize and setup the board
# player assignment and counter initializations

board = ChessBoardSetup()
turns = 0
N = 75
#currentWhite = True
# main game loop - while a player is not in checkmate or stalemate (<N turns)
# below is the rough looping strategy
while turns < N:
  #clear_output()
  DrawBoard(board)
  # write code to take turns and move the pieces
  if currentWhite == False:
    move = GetRandomMove()
  elif currentWhite == True:
    move = GetMinMaxMove()
  print(move)
  board = MovePiece(move[0][1], move[1][1], move[0][0], move[1][0])
  if(board[move[1][0]][move[1][1]]) == '.':
    turns += 1
  else:
    turns = 0
  
  DrawBoard(board)
  currentWhite = not currentWhite
  time.sleep(.5)

# check and print - Stalemate or Checkmate

"""#Submission Instructions

1.   Complete all tasks above - **File MUST contain the output for ALL cells**
2.   Export this notebook as .ipynb
      (File > Download as ipynb)
3.   Upload the .ipynb file on Blackboard

##Rubric

*   (10 points) Chess Board Setup
*   (50 points) Chess Rules Setup
*   (10 points) Random AI
*   (50 points) MinMax AI (2-ply)
*   (05 points) Game Main Loop - Random vs MinMax
*   (15 points) Extra Credit - 4-ply MinMax + alpha-beta pruning
"""